import {
    QueryDefinition,
    MutationDefinition,
} from '@reduxjs/toolkit/dist/query'
import {
    ApiEndpointQuery,
    ApiEndpointMutation,
} from '@reduxjs/toolkit/dist/query/core/module'
import {
    UseQuery,
    UseMutation,
} from '@reduxjs/toolkit/dist/query/react/buildHooks'

export type FetchError = {
    message: string
    status: number
}

// Query
export type InferUseQuery<E> = E extends ApiEndpointQuery<infer QD, any>
    ? UseQuery<QD>
    : never

export type InferQueryArgs<E> = E extends ApiEndpointQuery<
    QueryDefinition<infer A, any, any, any>,
    any
>
    ? A
    : never

export type InferQueryResult<E> = E extends ApiEndpointQuery<
    QueryDefinition<any, any, any, infer Res>,
    any
>
    ? Res
    : never

export type UseQueryOptions = {
    pollingInterval?: number
    refetchOnReconnect?: boolean
    refetchOnFocus?: boolean
    skip?: boolean
    refetchOnMountOrArgChange?: boolean | number
}

export type UseQueryResult<T> = {
    originalArgs?: unknown
    data?: T
    error?: FetchError
    requestId?: string
    endpointName?: string
    startedTimeStamp?: number
    fulfilledTimeStamp?: number

    isUninitialized: boolean
    isLoading: boolean
    isFetching: boolean
    isSuccess: boolean
    isError: boolean

    refetch: () => void
}

// Mutation
export type InferUseMutation<E> = E extends ApiEndpointMutation<infer QD, any>
    ? UseMutation<QD>
    : never

export type InferMutationArgs<E> = E extends ApiEndpointMutation<
    MutationDefinition<infer A, any, any, any>,
    any
>
    ? A
    : never

export type UseMutationTrigger<T> = (arg: any) => Promise<
    { data: T } | { error: FetchError }
> & {
    requestId: string // A string generated by RTK Query
    abort: () => void // A method to cancel the mutation promise
    unwrap: () => Promise<T> // A method to unwrap the mutation call and provide the raw response/error
    unsubscribe: () => void // A method to manually unsubscribe from the mutation call
}

export type UseMutationResult<T> = {
    originalArgs?: unknown
    data?: T
    error?: unknown
    endpointName?: string
    fulfilledTimestamp?: number

    isUninitialized: boolean
    isLoading: boolean
    isSuccess: boolean
    isError: boolean
    startedTimeStamp?: number
}
